### ISSUE TITLE
Site is eating resources while scrolling

### ISSUE THREAD

**Issue by atbe** [SpartaHack/SpartaHackAPI#15]
Hi!

I brought this issue up last year when I was on the site for the first time. When scrolling on the website's main page (and possibly other pages), the websites demands _much more_ CPU than one would deem necessary.

[Here is a video.](https://dl.dropboxusercontent.com/u/79887194/spartahack_website.mp4)

I have a feeling this is due to the misuse of an `onscroll event`. 
By using the same code base as the old website, the bug has carried on. 

I'm not trying to haggle anyone, and I apologize if I come off that way. I just don't think websites should put computers under more stress than they need to for the sack of the user. Shouldn't we care about the quality of our website, assuming we're true `hackers`?

Thanks,

\- @be

**Comment by bogderp** [comment]
Hey!

I believe I remember seeing your email, rest assured that we are not using the same code base as last year. Last year's website was a learning experience and was a first endevor into Ruby on Rails for our developers. 

This year we are starting from scratch with the website. That being said this repository is the home of the new API we are creating for the apps and the website to hit. SpartaHack 2017's Website can be found at SpartaHack/Spartahack-Website. 

Thanks for taking the time to let us know of this issue! We'll make sure performance is a priority for  future iterations of the website!

Bogdan
Tech Director

**Comment by milesjos** [comment]
Seeing as this does not pertain to the API, I am going to close this issue

**Comment by atbe** [comment]
Oh you're right, sorry for not paying attention to my current repo.

I appreciate the awesome work on Spartahack. Thanks.

**Comment by bogderp** [comment]
Just an update: I've fixed the performance issue on the 2016 site. Let me know if it performs better for you!
